apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proseed-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/skkuding/proseed
      targetRevision: main
      path: infra/k8s/api
      kustomize:
        images:
          - ghcr.io/skkuding/proseed/api:3013d61c7199fb629c1b38151629c02a3676d87b
  destination:
    server: https://kubernetes.default.svc
    namespace: proseed
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
