apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proseed-web
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=ghcr.io/skkuding/proseed/web:prod
    argocd-image-updater.argoproj.io/web.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/skkuding/proseed
      targetRevision: release
      path: infra/k8s/web
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: proseed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
