apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: proseed-aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: proseed-aws-credentials
            namespace: external-secrets
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: proseed-aws-credentials
            namespace: external-secrets
            key: aws_secret_access_key