apiVersion: v1
kind: Secret
metadata:
  name: dingdong-aws-credentials
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "aws-credentials/dingdong-aws-credentials"
type: Opaque
