apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dingdong-aws-credentials
  namespace: aws-credentials
spec:
  encryptedData:
    aws_access_key_id: AgDKYJ52Ua+yRVE+zoFCq8zkpzM6n6FryFazMhdFTNDIPH3N/JBsx/aBnP7XV3v5+nbY+eEKt+7MHMVenXnAyi9WcKmSRTdgto/Ax1D7quijXid5UWLX6/RD2F6TILOGQIqB3LpMdHT4uhv0jgeZ5pFyqv+WrkHb5qkOwFSdBX7wIynsg/OLBZZ8j5TIt7Lh4QkaoITvlrP0piaA8gYsn+Xz6rLZwcgGtZZKoGwCS/cktiTSnZQaJYppm3S/Q4B18VrYvH8qO+VVlRdXM35AdmK0BK2tXq5ZQ/mQ1LFtzP+b8iLpSbw82vxzSfkQSHWpnmNB8CWUY0QZMtBVj+lpre7qN1tiHW7rBeil/gMkojfqse70gqLhq6p42bJFm6RXlG7Rl6tSSr+KZbGCwnqSlJjKFiHWf+KzHlzJ6cNCxdN68GpH4t7CuHCz6Gc5Ax74T2QEugnU3wG+H451XKLdOJjMo8thCmpjFXHrhwg01y3Yd4a+oMrhb+RErqWFjcynYX2saKlFenKfZS6z2z2F5WufROuWx5PI9D1zC3OIMbsvRr21/22zTjLSLNTwJD5x4JheLG1TiJTwPVHlVN/K9RXzWevAEn5xQopjFnKAWVbWUNXZDYbJLjEYZPsDQ1dRnUcD/EzfQam7zmDyaoSviglbfIKvqBtbJFHZirlHNYAz7nJNKOTV5MXQj9nZSI7TCt4aCDsq2ib0mh7CcqVTVGaokYGH2w==
    aws_secret_access_key: AgAEPjGNnZ50ENPK1KLdE34FiYdE4343RZW+VgIj3An5/Tw6sebzYEWM5B/GnsolsYp2kZ1i+ibUgd2huT4Tzz0rlH0Yppr2qSmJsF8WNEUKXAG0C6j6kEsSHDZq3wqDDeA2gs88B/aXEUUooLSKw9nXR1WYqwB+oIoAjfzJQoiRPiIykA1GVSXm6Fxy04zqNY/D4DtLxdNKHpzam93dXkNfow2JMh1J1pWz/mkCtfLAmfuofLHM8qtzMxWypRGjEivulvLEMXm1tfOWKNMhb6KrwHGzOWiovMZt8KG2MIKpYe35vVQPqXWoCfkvKZSTEvPZHFTm7PHSOvPjpzZBlIKgWe+LctZSyx3nB+hJDCt1C2MQt3rXOAHsWThHb138BfydzWY4KcC7V6ALw6ZODbGyGe5YEIxxGxVTrBxHI66Zg+prRPtnbZQzcZ9PecgYoL0pWp1PC1Qt/eaxHu+XEpJRtDRk2FRxpOqnokCX9uq2dKUTaJJysC5iau7Ec2StBSEwDRptnohuIzXUhb+xhmd3z06o91lxAxCo45qwe4V72H5LjvTKPslH5uiM0SdQbZvHnqUdHDKooTQYrDYDhNpFvphyiQLI+hcmtf1By1udDGcUvLyOra5R3V3Dko3ZRcyDj6HEMZu3pTpVFANSQZ+jAXZtG/Vfv3/UYZT7tA5/5K3WvSS0NDxDi5yIm7/cXpfuvDNqp0nWHTw7hqGanlA24iUR4TnO7OdqflqXLjFFm1LoBTM8gki2
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: dingdong-aws-credentials
      namespace: aws-credentials
    type: Opaque
