apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proseed-aws-credentials
  namespace: aws-credentials
spec:
  encryptedData:
    aws_access_key_id: AgCRD+p9FO1+SkDQSgbFH4BwMJ1i3QYbNPh/3hlZfhXYPTKUPWTvFTRWc7zEbRobiH/0DqO8VqpsdBrL4cEKZR/mjBkK979xNqbLB0UVlZvvSJDl6cy+P8FVdeaSCUYWzauH+Rxfiso91npXGZQIso+uu5/uxwTWK3H4HjsexeDY5kVF7tdr501RFFws9KlvOjtQBGzVCUW/I2BXCKCgfbOsNrhQTb5qdBoTK/4osC3kib0z3NTRVoP8Tm9lKsFJyx24W0CkgxIbwLSu90R4zBoOvDti/DAY0StO81JYe/jY9m85JypAS1JTaZ8ifp82NbdZE4IuYeBwnKHc2F2uGcPjU7OllTDPbkO9PQ+paWbCyvGfuFh+cjqzABZCdnkP48V+RE/7aWsrMA3lktI8RbS6c5Q2ugfRv6jUjW9CXAdxpSxkZerLHRMHLIHoTIv2hi1f53zGyZB8r6M2SVVirXmO7MADhDSN9jfOBGrXdjjRGK2G7oD/R5mbzru1pMyO05JIJDlo3GAfU9Z/s3SYOwiTXh8ulKkmP94/GvYYaLkIPCGwf2ZNp3Eli9EV5reevMPBtOolnME1PuyK1Vm5F5tHY/0lBCRPsHQ7+fBP2fyNXKKs6k6dq8OQ3lxV6ykYanEUrbMUM9MciB9aN8I6vHAYrbB0CqLWf7aJ+6AfmaqXU01+bWAjEYX/Caeo17xE6B4MbuoH3TbsaWJaT12x7S3xy7tnAg==
    aws_secret_access_key: AgBZar90qwhlyg9uDnvYbWeA7rjl81NhbSjOjvMpjO3QBNmdLa9rEX709bYMV0c7QNGFwo0a2KAe/nrWbPkWp3oyMReGwwYb9DYhmoDvTXoInXZdhUqoI+0EDWXw9XLePEfnGeACqjhaIz6HnPFO+TpM6s6LvnXIg72CKMSo0xWF+genxXSikyQzIIkp3VG9pJba/ryMsfRstmVmXxLCxIKDn09H8SxOroQYLd7KdrOZm2DhEt+kM0+jCNaezNxDz8B0sh4mjTTn6c4vyOkOUuzL6pPvJu+Nx7kL2A7vUdnIQJihxJ+5/hsXkQS5kSjBS0qang4SQCi6y8b0sYu0qUdiIpbrX75gQYPqsyCyOw2QUjmOqtBNmLycHZspyw78MLV3xXhWAVC6hDFA+b3j/o4pg7yDr3Nik7Fq979A7KO4ulLfmBCJWD6Eez9/FfI+PDnMGX4GE5QfXMCYpGdgT6qcq5vBddJ9mqiQb8eS+VtBn86c9go5NemQECWSlNIpzZ1JBe1DJUorVkA7YV36/39qaKk4grpMGzTPW9Dc/g3/d6jEXNetSY5oxKXLgCVITPqIja5K3VJIuwRqRoS+uqKMcR7ti1CZX9f6rTg3hX+QpTXtGi5xCFB6W/huYj+h93hL432NxEeRBOeoACzuxSBuP9s1VecTQkxh4z6vNla+IXRNPYtXPsPGRvXkC3zxDMuUaikWId8J6EFAtlaEseVRVmdj3fT13PcI1EU2j4HapGfgE0F4OYg5
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: proseed-aws-credentials
      namespace: aws-credentials
    type: Opaque