apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proseed-aws-credentials
  namespace: aws-credentials
spec:
  encryptedData:
    aws_access_key_id: AgCTnoSkKkt6s97KEl753CiPamFRwMFNZKEsvLoNkEylpQmc/v579he3OxykTHJ0WM7Cu+wDYqOzSj3HxGBRYCUWY50NJa+fUjRXjoRX4N1JsFm+76ZiBzV7OSr4Ldwil0xV/DJcbIjsSDzzfy1ZdfITKwW79AK4WRUmjN/67oWWUxzr0t3BSVEIQFuPcvaGxWpKbVbFPN06qfJeCfA7dS2qfynazgguUIlT5vN0wvO6wKaBeS2+W1xNNqIQwxIiOKYUnQIsNDY3LqjfdkuT6DOGqY6yjDUP5ZqabxnM8NR4MWSV1BUTPfIhNJ1a2y6IY8+ICUwcEl5FURpA5i93RcRDwuaZjZ9Jqw401igo9CNUNWXtx8dT69Zs17psUTjaUwt364poeymHhN4S/GZg+nGO4z9JuN5hGoY3qIDUeWdfOinkQu0bi62iRoZVjVnhExfzY4FXiWDeYcRdJOp65SEQ8hF6wRDbUclEhgr77BRApG/TCEP6AdsGS07e4HbPaNRx1zgleFTjyK7+NfOx7/ucNhb17icasV8cgXh5bWO8uSEbUnXAZdoo3W7H1ay3nCpae6GSbjeU02lDyXZYBan6okT48z4xt5Iy1wk1G5WdhoniqNCHqk/MBfoBwS2IXq5HG3EqVaA2emRirA1m7+B0VWKJP/9HVWu8RHy5owTKMUTgGS+E8OSqLKoE6q9cwO7aJgSRlOk3U5Z2uWOESU+JcAEWnA==
    aws_secret_access_key: AgCq2zrYMi9mK+Q/QnViCvHilcxG34SyI4CEgFh9lv3+c8EarQoaxbWR6qC9weYTKp+2aAfZOkaBh5vKuTNJhhh/wXOJFEbY4PHZtTyy+KpsXdZluG+WHu8blrh9eVkm/RsS2GDMUiCbooonh82aecZfqpJGCUaBPbe+C4uSqZlu9LHXQG+hcnMge1Pq2Y6EDF90eBS9Oeg0FBQnvPu+cTHjTLGVuL+pryr5qTx4oqUlLO/3bai5yVHxINAy8MLwSjT4yom3gsVyhqgDLUwfbK4DAiE6DfY/LMOWkxHNz0i0tARYtUQy/8UlzLYOpK47HKMCQtg1EKyw/EV1j7PO8+9YfLO49LiLbpI7z68scWc51BulqMLjzJmGfHTjIryR4eXNWWo4cSXWMmDNu3QcW2cY/oqHOCeIm1d0h+lmGswjwEr8LdgwbTgn+YeQXZoyE83WzUqCFRj8m5wmPgi1Tj/aMkTWFIJYFx45ox8zbdRxaEs5FpC2jBLNM6FK7wRu29pg7oTg+CAOdcQaavUMat8qzAuI0pzBzuP+pWUTtDYqO79PEy8A1+HPWw28z3lrkVTnC4kT1M5mK4btemHy7xZKkKFvEerGFXgG4O9wTHJqSLdzCUtalTmUYQr6QcYgmg1YTYHL7pfSPTWeBhCSB3+ax7TuMgDi5o3+A3+HxWrNQkcVzOk16xxKUWRKoBT/FLChvH/TIYteai9o2cSBTgKDs9Qp19hjB3CZs7qncqdlkqtojRFJ5Zz7
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: proseed-aws-credentials
      namespace: aws-credentials
    type: Opaque