apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: skkuding-aws-credentials
  namespace: aws-credentials
spec:
  encryptedData:
    aws_access_key_id: AgByzKg+tuSoG2P0KWGfnlNeh7RZfcxrJv4wQZhsm1S/fZ/aR9MJJ5dD8Ugi78mB3S21FpXylGzTj6dMLkCgQM3Xj5iMKItbBgoN1yOSbu9oHopwqSRx7RQ/yXrMThooAlXAjU5g4Wu+O0f86HXeUUDTYc3MVkpuGiIuia1UfIxhLKuHKM4gvWnv0LXBThTf/wXBfofp3LdAVC2OK24tFTmTe3H971njEjSgU+1ytYeLc2sJeIFMU2MzR/N7qsB6H7SPeOQKXFDcH+NZFHWZaTkiwBD8Umxg8J7II/jO2EJDRQXTFercTh3hCVfHC5BPE1XhJ0tYkT3SQUIe19gfjcMH8VQNvr+ZcgWkZ3aJX/hQd5xaVtX6MlzrMjpWOpFRR2f5IwRqzDOCsWbKKUuen+u6J9ehGejPVHExKQD7+HQsy6Pajue3EdH4Kt/xPCQee5sjL65ffAxp37ArSmCMHy6mVLCbfxI+mLmLzojIGoQWXMADo8VtiW7KEG1KblPevr3hrMpCqKeXaaPZiD1tAKXNgH8+gSyXUJubgx7hWFqSK7r0DXRjznUyPpEtsE9FHdnMFM2nKDGjKFTZ0F/JcjrRgvBxdK6utKYEbsHc9adUSE+ujEwShYGfYQ3DE+DRzNDureHVLSyf18FQ/Wnzz4hksgE5ajlK2JjNWpSPzLgqj54QycL8DMWcCb22MiBAwXswsA3sBlDCPon0qChhS+VehlRSmQ==
    aws_secret_access_key: AgArAKGqLuMx4tpw5ivbcuCCjR/Ywr2TOSGPjF2P36oKXPIrE7+dgGVtX+2YUm/1CSGqV4BytwG3YtNaxXSafMC82V4qBnRhSVOrhUHL3nyBATG2m4bKmF5vJOy8EAtwy7t/2I1y6Wj9HdKZR9HwL2b3IEEeCV2SkiYsIpKI4JQQzlG1kTbzlyI20rxQPjDex7pxCMWvKoKDQG4VSYRozgu79CL1ttBiEKtksWiW9Nmb3MnsLStKMHEcy95U3zyXPQLm0z7TciNICav70DhuOvumccX9LHKjHPVMrLYlxpD31oamR0rl6dwhGd73Y+NW83BLeGKCx7lJ/4U4H7bU9kXrQKbVwLVaVAdOsNoMHcbjkKZtdPIemQ57arUBE7nTYN5q9xyicjZITqRbuOosaQHBoVl1dXvTmtJyN1vVs/ElESvrDO9txX0kCtLJoo9VnFoKhMgu+c9SAVmIPynagzDCTxaHDAEJtM1fCL4ugWi33nn8BhGO9+4fsLe/U5xvc80BqRQhBNOYFmoLudaHvlvJkCOu37xX4kKtZKeTIFa3nm0o+D4V9PD0HQohkSeioyuIzLcgkdQlelHmXjediUVZIPJPbe+jf7QnFKxLJPRHDFRBO+JUxMzEq3OCoVDDkjz4Rl3W4e0XTKBAQDQQJToKjPHe2yFBcZ7WQ+aFW6nHAmw/5MDKIMx6EJNGnl0vhHlPHA+ZlA5ww1LKmcua2uxbXEEJfGiyMb/qj3+i344/i3Yj8wfVE2dp
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: skkuding-aws-credentials
      namespace: aws-credentials
    type: Opaque